set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_BUILD_TYPE release)

if("${PORT}" STREQUAL "benchmark")
  set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DRUN_HAVE_POSIX_REGEX=0)
endif()
