#!/bin/bash

set -e

if ! command -v brew >/dev/null; then
  echo "Please make sure to run on a system with 'brew' on the PATH!"
  exit 1
fi

echo "==> Installing system dependencies with Homebrew..."
brew install \
  automake \
  autoconf-archive \
  ccache \
  nasm \
  ninja \
  pkg-config
