#!/bin/bash

set -e

echo "==> Installing system dependencies with APT..."
sudo apt-get update
sudo apt-get install -y \
  autoconf-archive \
  autotools-dev \
  ccache \
  cmake \
  '^libxcb.*-dev' \
  libx11-xcb-dev \
  libglu1-mesa-dev \
  libxrender-dev \
  libxi-dev \
  libxkbcommon-dev \
  libxkbcommon-x11-dev \
  mesa-common-dev \
  nasm \
  ninja-build
