#!/bin/bash

cd "$(dirname $0)/.."
set -e

if [ -z "$VCPKG_ROOT" ]; then
  export VCPKG_ROOT="$(pwd)/vcpkg"
fi

export VCPKG_OVERLAY_TRIPLETS="$VCPKG_ROOT/overlay/triplets"
export VCPKG_OVERLAY_PORTS="$VCPKG_ROOT/overlay/osx:vcpkg/overlay/ports"

"$VCPKG_ROOT/vcpkg" "$@"
